# 音声抽出プロセス設定ファイル
# Usage: python process_audio.py --config config/audio_extraction.yaml

# 音声抽出設定
audio:
  sample_rate: 16000      # サンプリングレート（Hz）
  channels: 1             # チャンネル数（1=モノラル, 2=ステレオ）
  format: "wav"           # 出力フォーマット
  codec: "pcm_s16le"      # 音声コーデック
  quality_level: "standard"  # 品質レベル (standard, high)

# 処理設定
processing:
  chunk_size: 30          # 大容量ファイル用チャンクサイズ（秒）
  timeout: 300            # タイムアウト（秒）
  cleanup_temp: true      # 一時ファイル自動削除

# 音声境界検出設定
speech_detection:
  enabled: true               # 自動検出を有効にする
  check_interval: 120         # チェック間隔（秒）
  max_check_duration: 600     # 最大チェック時間（秒、10分）
  segment_duration: 120       # セグメント長（秒）
  
  # Whisper設定
  model_size: "base"          # Whisperモデルサイズ
  language: "ja"              # 言語設定
  temperature: 0.0            # 温度パラメーター
  beam_size: 1                # ビームサーチサイズ
  
  # 判定閾値
  language_probability_threshold: 0.7   # 言語確率閾値
  minimum_segments_count: 3            # 最小セグメント数
  meaningful_text_min_length: 3        # 有意義なテキスト最小長
  
  # フォールバック設定
  default_skip_seconds: 180   # デフォルトスキップ時間（3分）

# ログ設定
logging:
  level: "INFO"           # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"