# ハイライト検出プロセス設定ファイル（標準）
# Usage: python process_highlights.py --config config/highlight_detection.yaml

# ハイライト検出設定
highlight_detection:
  emotion_change_threshold: 0.1      # 感情変化検出閾値
  high_emotion_threshold: 0.2        # 高感情閾値
  keyword_weight: 3.0                # キーワード重み
  duration_weight: 1.0               # 継続時間重み
  min_highlight_duration: 0.5        # 最小ハイライト継続時間（秒）
  min_highlight_score: 0.1           # 最小ハイライトスコア
  max_highlights: 15                 # 最大ハイライト数
  min_confidence: 0.3                # 最小信頼度
  merge_distance: 1.0                # 統合距離（秒）
  config_name: "standard"            # 設定名
  
  # エンゲージメントパターン（カスタマイズ可能）
  engagement_patterns:
    questions:
      - "どう"
      - "なぜ"
      - "何"
      - "どこ"
      - "いつ"
      - "誰"
      - "どれ"
      - "どの"
      - "？"
      - "?"
    exclamations:
      - "！"
      - "すごい"
      - "やばい"
      - "ヤバい"
      - "マジ"
      - "本当"
      - "ほんと"
      - "えー"
      - "うわー"
      - "おー"
    programming_terms:
      - "エラー"
      - "バグ"
      - "デバッグ"
      - "コード"
      - "プログラム"
      - "アルゴリズム"
      - "データ"
      - "関数"
      - "クラス"
      - "変数"
    completion_markers:
      - "完成"
      - "成功"
      - "達成"
      - "解決"
      - "できた"
      - "動いた"
      - "うまくいった"
      - "終了"

# ログ設定
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"